apiVersion: v1
kind: Namespace
metadata: 
  name: nanoacre
  labels: 
    name: nanoacre

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nanoacre
  name: nanoacre
  namespace: nanoacre
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  selector:
    app: nanoacre
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanoacre
  namespace: nanoacre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanoacre
  template:
    metadata:
      labels:
        app: nanoacre
    spec:
      containers:
      - image: eu.gcr.io/warm-melody-260208/nanoacre
        imagePullPolicy: IfNotPresent
        name: nanoacre
        ports:
        - containerPort: 9000 
          protocol: TCP
        resources: {}
      imagePullSecrets:
      - name: gcr-json-key
